set(CXX_LINKER "CXX")
set(NETCDF_PATH "/usr/lib/x86_64-linux-gnu/netcdf/mpi")
set(NETCDF_C_PATH "/usr/lib/x86_64-linux-gnu/netcdf/mpi")
set(NETCDF_FORTRAN_PATH "/usr/lib/x86_64-linux-gnu/netcdf/mpi")
set(HDF5_PATH "/usrlib/x86_64-linux-gnu/hdf5/openmpi")
set(PNETCDF_PATH "")
set(BLASLAPACK_LIBDIR "$ENV{BLASLAPACK_LIBDIR}")
string(APPEND FFLAGS " -fallow-argument-mismatch")
string(APPEND CFLAGS " -I/usr/lib/x86_64-linux-gnu/netcdf/mpi/include -I/usr/include")
string(APPEND FFLAGS " -I/usr/lib/x86_64-linux-gnu/netcdf/mpi/include -I/usr/include")
string(APPEND SLIBS " -Wl,-rpath=/usr/lib/x86_64-linux-gnu/netcdf/mpi/lib -L/usr/lib/x86_64-linux-gnu/netcdf/mpi/lib -lnetcdf -lnetcdff")
string(APPEND SLIBS " -L/usr/lib/x86_64-linux-gnu -lblas -llapack")
set(ALQUIMIA_PATH "$ENV{ALQUIMIA_PATH}/build/alquimia")
set(PFLOTRAN_PATH "$ENV{PFLOTRAN_PATH}")
string(APPEND FFLAGS " -I${ALQUIMIA_PATH} -I${PFLOTRAN_PATH}")
string(APPEND CFLAGS " -I${ALQUIMIA_PATH} -I${PFLOTRAN_PATH}")
string(APPEND SLIBS " -Wl,-rpath=${ALQUIMIA_PATH} -L${ALQUIMIA_PATH} -Wl,-rpath=${PFLOTRAN_PATH} -L${PFLOTRAN_PATH}")
